# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83c0e87ac7482a0c5fa3e92174f4b0861a67f646bdc1c4ad185f366ee492d6b7b7aaa19f9116e874f0d6cdcd95ab5f0f3f61006796a21de2b645287ac64a6897

test:
  secret_key_base: 05310b5512822d8b842c9b106e4acea3d59b020cc6493bbf740aff3567965a563b61e6c2b5bfd8e49d8752a75915674f4cbe0dd20a6c52cbb433c89b03ad1e1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
